In [ ]:
class Vector:
  def __init__(self, *lst):
    self.data = lst

  def __str__(self):
    return f"Vec{self.data}"

  def __add__(self, other):
    return Vector(*[a+b for a, b in zip(self.data, other.data)])
  
  def __sub__(self, other):
    return Vector(*[a-b for a, b in zip(self.data, other.data)])

  def __mul__(self, other):
    if type(other) == Vector:
      return sum(a * b for a, b in zip(self.data, other.data))
    return Vector(*[a *other for a in self.data])

  def __rmul__(self, other):
    return Vector(*[a *other for a in self.data])

a = Vector(1,2,3)
b = Vector(2,3,4)
c = a + b
d = b - a
e = b * 4
f = 3 * b
g = a * b

print(a, b, c, d, e, f, g)

In [ ]:
import numpy as np


a = np.array([1,2,3])
b = np.array([2,3,4])

print(a+b)
print(a-b)
print(a*4)
print(a*b)
print(a.dot(b))
print(sum(a*b))

print(np.zeros([3,4]))
print(np.ones([3,4]))


In [ ]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[3,2,1],[1,2,3]])

print(A+b)
print(A-b)
print(A*b) # 원소곱
print(B.T) # 전치
print(A.dot(B.T)) # 행렬곱

[[ 3  5  7]
 [ 6  8 10]]
[[-1 -1 -1]
 [ 2  2  2]]
[[ 2  6 12]
 [ 8 15 24]]
[[3 1]
 [2 2]
 [1 3]]
[[10 14]
 [28 32]]
